export class AppColors {
  static readonly BACKGROUND: string = '#FAF8FD';
  static readonly SURFACE: string = '#F0EFF4';
  static readonly SURFACE_STRONG: string = '#E8E8EF';
  static readonly PRIMARY: string = '#5269A8';
  static readonly PRIMARY_SOFT: string = '#DDE4FF';
  static readonly HEART: string = '#F04444';
  static readonly HEART_SOFT: string = '#F39AA2';
  static readonly ERROR: string = '#C52A22';
  static readonly TEXT: string = '#17181C';
  static readonly TEXT_MUTED: string = '#62656E';
  static readonly DIVIDER: string = '#FFFFFF';
  static readonly WHITE: string = '#FFFFFF';
}

